
import { Notification, FilterOption } from "../types/notifications-types";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    priority: "critical",
    category: "flood",
    title: "LŨ QUÉT KHẨN CẤP",
    location: "Phường Hòa Xuân, Quận Cẩm Lệ",
    timestamp: "2025-12-07T15:45:00",
    timeAgo: "5 phút trước",
    isRead: false,
    description: "Mực nước dâng cao 85cm tại khu vực Hòa Xuân. Nguy cơ lũ quét cao. Yêu cầu di dời dân cư khẩn cấp.",
    affectedArea: "~2.8 km²",
    waterLevel: 85,
    actions: {
      viewMap: true,
      getDirections: true,
      viewDetails: true,
    },
  },
  {
    id: "2",
    priority: "high",
    category: "water_level",
    title: "MỰC NƯỚC SÔNG HÀN DÂNG CAO",
    location: "Cầu Rồng, Quận Sơn Trà",
    timestamp: "2025-12-07T14:50:00",
    timeAgo: "1 giờ trước",
    isRead: false,
    description: "Sông Hàn đạt mức cảnh báo 2 tại khu vực Cầu Rồng. Mực nước 65cm và tiếp tục dâng.",
    waterLevel: 65,
    affectedArea: "~3.5 km²",
    actions: {
      viewMap: true,
      getDirections: true,
      viewDetails: true,
    },
  },
  {
    id: "3",
    priority: "high",
    category: "flood",
    title: "NGẬP LỤT KHU DÂN CƯ",
    location: "Phường Hải Châu 1, Quận Hải Châu",
    timestamp: "2025-12-07T14:20:00",
    timeAgo: "1.5 giờ trước",
    isRead: false,
    description: "Đường Lê Duẩn đoạn qua trung tâm TP ngập 45cm. Giao thông ùn tắc nghiêm trọng.",
    waterLevel: 45,
    affectedArea: "~1.8 km²",
    actions: {
      viewMap: true,
      getDirections: true,
      viewDetails: true,
    },
  },
  {
    id: "4",
    priority: "medium",
    category: "weather",
    title: "DỰ BÁO MƯA LỚN",
    location: "Quận Thanh Khê, Quận Liên Chiểu",
    timestamp: "2025-12-07T12:50:00",
    timeAgo: "3 giờ trước",
    isRead: true,
    description: "Mưa dông, gió giật mạnh cấp 6-7 từ 16h - 20h hôm nay. Đề phòng ngập úng cục bộ.",
    actions: {
      viewMap: true,
      viewDetails: true,
    },
  },
  {
    id: "5",
    priority: "medium",
    category: "traffic",
    title: "GIAO THÔNG TẮC NGHẼN",
    location: "Đường Điện Biên Phủ, Thanh Khê",
    timestamp: "2025-12-07T11:30:00",
    timeAgo: "4 giờ trước",
    isRead: true,
    description: "Ngập nước 38cm tại đoạn Ngã ba Huế. Xe cộ di chuyển chậm, tránh khu vực nếu có thể.",
    waterLevel: 38,
    actions: {
      viewMap: true,
      getDirections: true,
    },
  },
  {
    id: "6",
    priority: "medium",
    category: "water_level",
    title: "TRIỀU CƯỜNG BẤT THƯỜNG",
    location: "Bãi biển Mỹ Khê, Quận Ngũ Hành Sơn",
    timestamp: "2025-12-07T10:15:00",
    timeAgo: "5 giờ trước",
    isRead: true,
    description: "Mực nước biển dâng cao bất thường. Hạn chế hoạt động tắm biển và du lịch ven bờ.",
    waterLevel: 42,
    affectedArea: "~4.2 km bờ biển",
    actions: {
      viewMap: true,
      viewDetails: true,
    },
  },
  {
    id: "7",
    priority: "medium",
    category: "flood",
    title: "CẢNH BÁO NGẬP ĐÔ THỊ",
    location: "Đường 2 Tháng 9, Quận Hải Châu",
    timestamp: "2025-12-07T09:40:00",
    timeAgo: "6 giờ trước",
    isRead: true,
    description: "Khu vực trung tâm từ biển Mỹ Khê vào nội thành có nguy cơ ngập 30-40cm.",
    waterLevel: 35,
    actions: {
      viewMap: true,
      getDirections: true,
    },
  },
  {
    id: "8",
    priority: "low",
    category: "weather",
    title: "THỜI TIẾT THUẬN LỢI",
    location: "Bán đảo Sơn Trà",
    timestamp: "2025-12-07T08:30:00",
    timeAgo: "7 giờ trước",
    isRead: true,
    description: "Khu vực Sơn Trà thời tiết ổn định. Mực nước giảm dần, an toàn cho hoạt động du lịch.",
    waterLevel: 22,
    actions: {
      viewDetails: true,
    },
  },
  {
    id: "9",
    priority: "low",
    category: "system",
    title: "CẬP NHẬT HỆ THỐNG",
    location: "Toàn bộ khu vực Đà Nẵng",
    timestamp: "2025-12-07T08:00:00",
    timeAgo: "8 giờ trước",
    isRead: true,
    description: "Hệ thống cảnh báo lũ lụt Đà Nẵng đã được nâng cấp phiên bản 2.5 với độ chính xác cao hơn.",
    actions: {
      viewDetails: true,
    },
  },
  {
    id: "10",
    priority: "medium",
    category: "traffic",
    title: "TẮC ĐƯỜNG NGẬP NƯỚC",
    location: "Cầu Trần Thị Lý, Quận Hải Châu",
    timestamp: "2025-12-07T07:20:00",
    timeAgo: "8.5 giờ trước",
    isRead: true,
    description: "Đường dẫn Cầu Trần Thị Lý ngập 32cm. Phương tiện lưu thông khó khăn vào giờ cao điểm.",
    waterLevel: 32,
    actions: {
      viewMap: true,
      getDirections: true,
    },
  },
];

export const FILTER_OPTIONS: FilterOption[] = [
  { key: "all", label: "Tất cả" },
  { key: "critical", label: "Khẩn cấp", color: "#DC2626" },
  { key: "high", label: "Quan trọng", color: "#F59E0B" },
  { key: "medium", label: "Thông báo", color: "#3B82F6" },
];
