// features/areas/data/all-areas-data.ts
import { Area } from "../types/areas-types";

export const ALL_AREAS: Area[] = [
  // ===== Khu vực hệ thống (map được với ZONE) =====

  // Zone 1: Hải Châu - Trung tâm
  {
    id: "area-hai-chau",
    name: "Quận Hải Châu - Trung tâm",
    location: "Trung tâm Quận Hải Châu",
    waterLevel: 2.5,
    maxLevel: 2.0,
    status: "danger",
    statusText: "Nguy hiểm",
    lastUpdate: "2 phút trước",
    forecast: "Mưa lớn, nguy cơ ngập nặng",
    temperature: 27,
    humidity: 92,
    rainChance: 95,
    isFavorite: false,
    district: "Đà Nẵng",
    // sensor trong zone-1: S_TP_01, S_NVL_01, S_NVL_02
    sensorCount: 3,
    affectedStreets: ["Trần Phú", "Nguyễn Văn Linh"],
    rainfall: "85mm/3h",
  },

  // Zone 2: Sông Hàn & Bờ Đông
  {
    id: "area-song-han",
    name: "Sông Hàn & Bờ Đông",
    location: "Dọc bờ Tây & Đông Sông Hàn",
    waterLevel: 2.0,
    maxLevel: 2.0,
    status: "warning",
    statusText: "Cảnh báo",
    lastUpdate: "3 phút trước",
    forecast: "Mưa vừa, nước sông dâng cao",
    temperature: 26,
    humidity: 88,
    rainChance: 80,
    isFavorite: false,
    district: "Đà Nẵng",
    // sensor trong zone-2: S_BD_01, S_BD_02, S_BD_03
    sensorCount: 3,
    affectedStreets: ["Bạch Đằng"],
    rainfall: "60mm/3h",
  },

  // Zone 3: Thanh Khê
  {
    id: "area-thanh-khe",
    name: "Quận Thanh Khê",
    location: "Khu dân cư Thanh Khê",
    waterLevel: 0.9,
    maxLevel: 1.5,
    status: "warning",
    statusText: "Nguy cơ thấp",
    lastUpdate: "8 phút trước",
    forecast: "Mưa nhỏ, ngập cục bộ một số điểm",
    temperature: 27,
    humidity: 82,
    rainChance: 60,
    isFavorite: false,
    district: "Đà Nẵng",
    // sensor trong zone-3: S_LD_01, S_DBP_01
    sensorCount: 2,
    affectedStreets: ["Lê Duẩn", "Điện Biên Phủ"],
    rainfall: "22mm/3h",
  },

  // Zone 4: Sơn Trà - Biển
  {
    id: "area-son-tra-bien",
    name: "Sơn Trà - Biển",
    location: "Ven biển Mỹ Khê, Sơn Trà",
    waterLevel: 0.5,
    maxLevel: 1.5,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "10 phút trước",
    forecast: "Trời âm u, có thể mưa nhẹ",
    temperature: 27,
    humidity: 70,
    rainChance: 30,
    isFavorite: false,
    district: "Đà Nẵng",
    sensorCount: 0,
    affectedStreets: [],
    rainfall: "8mm/3h",
  },

  // ===== Điểm cá nhân (không map với Zone) =====

  {
    id: "area-1",
    name: "Nhà riêng",
    location: "123 Nguyễn Văn Linh, Đà Nẵng",
    waterLevel: 10,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "5 phút trước",
    forecast: "Trời quang, không mưa",
    temperature: 28,
    humidity: 65,
    rainChance: 10,
    isFavorite: true,
    district: "Hải Châu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "5mm/3h",
  },
  {
    id: "area-2",
    name: "Trường ĐH Bách Khoa",
    location: "54 Nguyễn Lương Bằng, Đà Nẵng",
    waterLevel: 42,
    maxLevel: 50,
    status: "warning",
    statusText: "Cảnh giác",
    lastUpdate: "12 phút trước",
    forecast: "Mưa vừa, nguy cơ ngập nhẹ",
    temperature: 26,
    humidity: 85,
    rainChance: 70,
    isFavorite: false,
    district: "Liên Chiểu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "18mm/3h",
  },
  {
    id: "area-4",
    name: "Công ty ABC",
    location: "789 Trần Phú, Đà Nẵng",
    waterLevel: 15,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "8 phút trước",
    forecast: "Trời âm u, có thể mưa nhẹ",
    temperature: 27,
    humidity: 70,
    rainChance: 30,
    isFavorite: false,
    district: "Hải Châu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "10mm/3h",
  },
];
