
import { Area } from "../types/areas-types";

export const MOCK_AREAS: Area[] = [
  {
    id: "area-1",
    name: "Nhà riêng",
    location: "123 Nguyễn Văn Linh, Đà Nẵng",
    waterLevel: 10,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "5 phút trước",
    forecast: "Trời quang, không mưa",
    temperature: 28,
    humidity: 65,
    rainChance: 10,
    isFavorite: true,
  },
  {
    id: "area-2",
    name: "Trường ĐH Bách Khoa",
    location: "54 Nguyễn Lương Bằng, Đà Nẵng",
    waterLevel: 42,
    maxLevel: 50,
    status: "warning",
    statusText: "Cảnh giác",
    lastUpdate: "12 phút trước",
    forecast: "Mưa vừa, nguy cơ ngập nhẹ",
    temperature: 26,
    humidity: 85,
    rainChance: 70,
    isFavorite: false,
  },
  {
    id: "area-3",
    name: "Quận Hải Châu",
    location: "Trung tâm Quận Hải Châu",
    waterLevel: 55,
    maxLevel: 50,
    status: "danger",
    statusText: "Nguy hiểm",
    lastUpdate: "2 phút trước",
    forecast: "Mưa lớn, nguy cơ ngập nặng",
    temperature: 27,
    humidity: 92,
    rainChance: 95,
    isFavorite: false,
  },
  {
    id: "area-4",
    name: "Công ty ABC",
    location: "789 Trần Phú, Đà Nẵng",
    waterLevel: 15,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "8 phút trước",
    forecast: "Trời âm u, có thể mưa nhẹ",
    temperature: 27,
    humidity: 70,
    rainChance: 30,
    isFavorite: false,
  },
];
