// features/home/data/areas-data.ts
import { Area } from "../types/areas-types";

export const MOCK_AREAS: Area[] = [
  {
    id: "area-1",
    name: "Nhà riêng",
    location: "123 Nguyễn Văn Linh, Đà Nẵng",
    waterLevel: 10,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "5 phút trước",
    forecast: "Trời quang, không mưa",
    temperature: 28,
    humidity: 65,
    rainChance: 10,
    isFavorite: true,
    // type: "personal",
    district: "Hải Châu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "5mm/3h",
  },
  {
    id: "area-2",
    name: "Trường ĐH Bách Khoa",
    location: "54 Nguyễn Lương Bằng, Đà Nẵng",
    waterLevel: 42,
    maxLevel: 50,
    status: "warning",
    statusText: "Cảnh giác",
    lastUpdate: "12 phút trước",
    forecast: "Mưa vừa, nguy cơ ngập nhẹ",
    temperature: 26,
    humidity: 85,
    rainChance: 70,
    isFavorite: false,
    // type: "personal",
    district: "Liên Chiểu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "18mm/3h",
  },
  {
    id: "area-hai-chau",
    name: "Quận Hải Châu",
    location: "Trung tâm Quận Hải Châu",
    waterLevel: 2.5,          
    maxLevel: 2.0,
    status: "danger",
    statusText: "Nguy hiểm",
    lastUpdate: "2 phút trước",
    forecast: "Mưa lớn, nguy cơ ngập nặng",
    temperature: 27,
    humidity: 92,
    rainChance: 95,
    isFavorite: false,
    // type: "district",
    district: "Đà Nẵng",
    sensorCount: 5,
    affectedStreets: ["Đường 2/9", "Nguyễn Văn Linh", "Trần Phú"],
    rainfall: "85mm/3h",
  },
  {
    id: "area-ngu-hanh-son",
    name: "Quận Ngũ Hành Sơn",
    location: "Quận Ngũ Hành Sơn",
    waterLevel: 0.5,
    maxLevel: 1.5,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "10 phút trước",
    forecast: "Trời âm u, có thể mưa nhẹ",
    temperature: 27,
    humidity: 70,
    rainChance: 30,
    isFavorite: false,
    // type: "district",
    district: "Đà Nẵng",
    sensorCount: 3,
    affectedStreets: [],
    rainfall: "8mm/3h",
  },
  {
    id: "area-son-tra",
    name: "Quận Sơn Trà",
    location: "Quận Sơn Trà",
    waterLevel: 1.4,
    maxLevel: 1.5,
    status: "warning",
    statusText: "Cảnh báo",
    lastUpdate: "5 phút trước",
    forecast: "Mưa vừa, nước sông dâng cao",
    temperature: 26,
    humidity: 88,
    rainChance: 80,
    isFavorite: false,
    // type: "district",
    district: "Đà Nẵng",
    sensorCount: 4,
    affectedStreets: ["Võ Nguyên Giáp", "Hoàng Sa"],
    rainfall: "45mm/3h",
  },
  {
    id: "area-thanh-khe",
    name: "Quận Thanh Khê",
    location: "Quận Thanh Khê",
    waterLevel: 0.9,
    maxLevel: 1.5,
    status: "warning",
    statusText: "Nguy cơ thấp",
    lastUpdate: "8 phút trước",
    forecast: "Mưa nhỏ, ngập cục bộ một số điểm",
    temperature: 27,
    humidity: 82,
    rainChance: 60,
    isFavorite: false,
    // type: "district",
    district: "Đà Nẵng",
    sensorCount: 3,
    affectedStreets: [],
    rainfall: "22mm/3h",
  },
  {
    id: "area-4",
    name: "Công ty ABC",
    location: "789 Trần Phú, Đà Nẵng",
    waterLevel: 15,
    maxLevel: 50,
    status: "safe",
    statusText: "An toàn",
    lastUpdate: "8 phút trước",
    forecast: "Trời âm u, có thể mưa nhẹ",
    temperature: 27,
    humidity: 70,
    rainChance: 30,
    isFavorite: false,
    // type: "personal",
    district: "Hải Châu",
    sensorCount: 1,
    affectedStreets: [],
    rainfall: "10mm/3h",
  },
];
